apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: knative-eventing.packages.kadras.io.1.11.3
spec:
  licenses:
  - Apache 2.0
  refName: knative-eventing.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-knative-eventing/releases
  releasedAt: "2023-09-19T20:43:43Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-knative-eventing@sha256:72809b92f53974f5e4d2c6c68c9d91e93eaa08ea8ab95d9553bd48115f448efb
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        default_broker:
          additionalProperties: false
          description: Configuration for the default in-memory broker
          properties:
            enabled:
              default: false
              description: Whether to install the default in-memory broker
              type: boolean
            namespace:
              default: default
              description: The namespace where to install the default broker
              type: string
          type: object
      type: object
  version: 1.11.3
