apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: secretgen-controller.packages.kadras.io.0.18.1
spec:
  licenses:
  - Apache 2.0
  refName: secretgen-controller.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-secretgen-controller/releases
  releasedAt: "2024-09-23T19:59:51Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-secretgen-controller@sha256:f041a9b19a252e03ab5e8d6070a7aaacd3422a269e3c01e35a615e1fa67232c3
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 0.18.1
