apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: secretgen-controller.packages.kadras.io.0.19.2
spec:
  licenses:
  - Apache 2.0
  refName: secretgen-controller.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-secretgen-controller/releases
  releasedAt: "2025-05-30T18:30:26Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-secretgen-controller@sha256:a75097ef7dc675acb9144cd6b7c76fccfb3d7aa57969cf3b0ec36a0f48fe35df
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 0.19.2
