apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: secretgen-controller.packages.kadras.io
spec:
  categories:
  - secret management
  displayName: secretgen-controller
  longDescription: Provide CRDs to specify what secrets need to be on cluster (generated
    or not).
  maintainers:
  - name: Carvel team (see www.carvel.dev for team members)
  providerName: carvel.dev
  shortDescription: Secret generation and sharing
