apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: service-binding.packages.kadras.io.0.9.0
spec:
  licenses:
  - Apache 2.0
  refName: service-binding.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-service-binding/releases
  releasedAt: "2024-05-17T20:07:49Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-service-binding@sha256:b7455ad4ff23c63e51490b929ab88e3ca83272af7b17a70243463bb1a54afe54
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 0.9.0
