apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: workspace-provisioner.packages.kadras.io.0.2.1
spec:
  licenses:
  - Apache 2.0
  refName: workspace-provisioner.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/workspace-provisioner/releases
  releasedAt: "2023-08-20T14:07:00Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/workspace-provisioner@sha256:f3ae24dd72f9ac6194738683e8d5e0cc95c2c8d7e7b87e431bdd4f67f828f2a3
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        cosign:
          additionalProperties: false
          description: Settings for Cosign, used for signing and verifying OCI artifacts.
          properties:
            secret:
              additionalProperties: false
              description: Configuration for the Secret holding the Cosign key pair.
              properties:
                name:
                  default: ""
                  description: The name of the Secret holding the Cosign key pair.
                  type: string
                namespace:
                  default: ""
                  description: The namespace of the Secret holding the Cosign key
                    pair.
                  type: string
              type: object
          type: object
        git:
          additionalProperties: false
          description: Configuration to access the Git repositories used in the GitOps
            workflows.
          properties:
            secret:
              additionalProperties: false
              description: Configuration for the Secret holding the Git credentials.
              properties:
                name:
                  default: ""
                  description: The name of the Secret holding the Git credentials.
                  type: string
                namespace:
                  default: ""
                  description: The namespace of the Secret holding the Git credentials.
                  type: string
              type: object
            server:
              default: https://github.com
              description: The Git server hosting the Git repositories used in the
                GitOps workflows.
              type: string
          type: object
        namespaces:
          default: []
          description: Configuration for the namespaces the platform will provision
            and manage.
          items:
            additionalProperties: false
            description: Details about the namespace to configure.
            properties:
              name:
                default: ""
                type: string
            type: object
          type: array
        oci_registry:
          additionalProperties: false
          description: Settings for the OCI registry that the workspace will use.
          properties:
            secret:
              additionalProperties: false
              description: Configuration for the Secret holding the credentials to
                access the OCI registry.
              properties:
                name:
                  default: ""
                  description: The name of the Secret holding the credentials to access
                    the OCI registry.
                  type: string
                namespace:
                  default: ""
                  description: The namespace of the Secret holding the credentials
                    to access the OCI registry.
                  type: string
              type: object
          type: object
        service_account:
          default: default
          description: The `ServiceAccount` to be configured with credentials and
            roles in each workspace.
          type: string
      type: object
  version: 0.2.1
