apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: workspace-provisioner.packages.kadras.io
spec:
  categories:
  - environment provisioning
  displayName: workspace-provisioner
  longDescription: Provisions and configures workspaces for the platform users, such
    as application developers. A workspace can be a namespace or a virtual cluster.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Provisions and configures workspaces for the platform users.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/workspace-provisioner
    for community support.
