apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cert-manager-issuers.packages.kadras.io.0.2.0
spec:
  licenses:
  - Apache 2.0
  refName: cert-manager-issuers.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/cert-manager-issuers/releases
  releasedAt: "2023-06-04T15:25:37Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/cert-manager-issuers@sha256:0c8f82d9319e8cf4db2c991a2728eb752cacd57fa6785cebf0bc6a74f7c2a31b
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        letsencrypt:
          additionalProperties: false
          description: Settings for Let's Encrypt.
          properties:
            email:
              default: ""
              description: The email address that Let's Encrypt will use to send info
                on expiring certificates or issues.
              type: string
            include:
              default: false
              description: Whether to include a ClusterIssuer for Let's Encrypt.
              type: boolean
            staging:
              default: true
              description: Whether to use Let's Encrypt staging, recommended for non-production
                environments.
              type: boolean
          type: object
        namespace:
          default: cert-manager
          description: The namespace where cert-manager is deployed.
          type: string
      type: object
  version: 0.2.0
