apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: contour.packages.kadras.io.1.23.2+kadras.1
spec:
  capacityRequirementsDescription: Varies significantly based on number of Services,
    Ingresses/HTTPProxies, etc. A starting point is 128MB RAM and 0.5 CPU for each
    Contour and Envoy pod, but this can and should be tuned based on observed usage.
  licenses:
  - Apache 2.0
  refName: contour.packages.kadras.io
  releaseNotes: https://github.com/projectcontour/contour/releases
  releasedAt: "2023-01-13T16:32:44Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-contour@sha256:199401260a26831f6cefb5ace643b55278e77b5cf889b7ccd84f8f660d84679b
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        certificates:
          additionalProperties: false
          description: Settings for the TLS certificates for securing communication
            between Contour and Envoy.
          properties:
            duration:
              default: 8760h
              description: If using cert-manager, how long the certificates should
                be valid for. If useCertManager is false, this field is ignored.
              type: string
            renewBefore:
              default: 360h
              description: If using cert-manager, how long before expiration the certificates
                should be renewed. If useCertManager is false, this field is ignored.
              type: string
            useCertManager:
              default: false
              description: Whether to use cert-manager to provision TLS certificates
                for securing communication between Contour and Envoy. If false, the
                upstream Contour certgen job will be used to provision certificates.
                If true, the cert-manager addon must be installed in the cluster.
              type: boolean
          type: object
        contour:
          additionalProperties: false
          description: Settings for the Contour component.
          properties:
            configFileContents:
              default: null
              description: The YAML contents of the Contour config file. See https://projectcontour.io/docs/latest/configuration/#configuration-file
                for more information.
              nullable: true
            logLevel:
              default: info
              description: The Contour log level. Valid options are 'info' and 'debug'.
              type: string
            replicas:
              default: 2
              description: How many Contour pod replicas to have.
              type: integer
            useProxyProtocol:
              default: false
              description: Whether to enable PROXY protocol for all Envoy listeners.
              type: boolean
          type: object
        envoy:
          additionalProperties: false
          description: Settings for the Envoy component.
          properties:
            hostNetwork:
              default: false
              description: Whether to enable host networking for the Envoy pods.
              type: boolean
            hostPorts:
              additionalProperties: false
              description: Host port settings for the Envoy pods.
              properties:
                enable:
                  default: false
                  description: Whether to enable host ports. If false, http & https
                    are ignored.
                  type: boolean
                http:
                  default: 80
                  description: If enable == true, the host port number to expose Envoy's
                    HTTP listener on.
                  type: integer
                https:
                  default: 443
                  description: If enable == true, the host port number to expose Envoy's
                    HTTPS listener on.
                  type: integer
              type: object
            logLevel:
              default: info
              description: The Envoy log level.
              type: string
            service:
              additionalProperties: false
              description: Envoy service settings.
              properties:
                annotations:
                  default: null
                  description: Annotations to set on the Envoy service.
                  nullable: true
                aws:
                  additionalProperties: false
                  description: AWS-specific settings for the Envoy service. If infrastructure
                    provider is not 'aws', these settings are ignored.
                  properties:
                    loadBalancerType:
                      default: classic
                      description: The type of AWS load balancer to provision. Options
                        are 'classic' and 'nlb'.
                      type: string
                  type: object
                externalTrafficPolicy:
                  default: ""
                  description: The external traffic policy for the Envoy service.
                    If type is 'ClusterIP', this field is ignored. Otherwise, defaults
                    to 'Cluster' for vsphere and 'Local' for others.
                  type: string
                loadBalancerIP:
                  default: ""
                  description: The desired load balancer IP. If type is not 'LoadBalancer',
                    this field is ignored. It is up to the cloud provider whether
                    to honor this request. If not specified, then load balancer IP
                    will be assigned by the cloud provider.
                  type: string
                nodePorts:
                  additionalProperties: false
                  description: NodePort settings for the Envoy service. If type is
                    not 'NodePort' or 'LoadBalancer', these settings are ignored.
                  properties:
                    http:
                      default: 0
                      description: The node port number to expose Envoy's HTTP listener
                        on. If not specified, a node port will be auto-assigned by
                        Kubernetes.
                      type: integer
                    https:
                      default: 0
                      description: The node port number to expose Envoy's HTTPS listener
                        on. If not specified, a node port will be auto-assigned by
                        Kubernetes.
                      type: integer
                  type: object
                type:
                  default: null
                  description: The type of Kubernetes service to provision for Envoy.
                    If not specified, will default to 'NodePort' for docker and vsphere
                    and 'LoadBalancer' for others.
                  nullable: true
                  type: string
              type: object
            terminationGracePeriodSeconds:
              default: 300
              description: The termination grace period, in seconds, for the Envoy
                pods.
              type: integer
            workload:
              additionalProperties: false
              description: Envoy workload settings.
              properties:
                replicas:
                  default: 2
                  description: The number of Envoy replicas to deploy when 'type'
                    is set to 'Deployment'. If not specified, it will default to '2'.
                  type: integer
                type:
                  default: DaemonSet
                  description: The type of Kubernetes workload Envoy is deployed as.
                    Options are 'Deployment' or 'DaemonSet'. If not specified, will
                    default to 'DaemonSet'.
                  type: string
              type: object
          type: object
        infrastructureProvider:
          default: ""
          description: The underlying infrastructure provider. Options are aws, azure,
            docker and vsphere. This field is not required, but enables better validation
            and defaulting if provided.
          type: string
        namespace:
          default: projectcontour
          description: The namespace in which to deploy Contour and Envoy.
          type: string
      type: object
  version: 1.23.2+kadras.1
