apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: contour.packages.kadras.io.1.24.3
spec:
  licenses:
  - Apache 2.0
  refName: contour.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-contour/releases
  releasedAt: "2023-04-09T09:14:36Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --kube-api-qps=50
          - --kube-api-burst=100
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-contour@sha256:8ad525ebd8fe06e636056b13f386d96fe61e484a5acad42a93f0a44f71d85e5f
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        certificates:
          additionalProperties: false
          description: TLS configuration to secure the communication between Contour
            and Envoy.
          properties:
            duration:
              default: 8760h
              description: If using cert-manager, how long the certificates should
                be valid for. If `useCertManager` is false, this field is ignored.
              type: string
            renewBefore:
              default: 360h
              description: If using cert-manager, how long before expiration the certificates
                should be renewed. If `useCertManager` is false, this field is ignored.
              type: string
            useCertManager:
              default: false
              description: 'Whether to use cert-manager to provision TLS certificates
                for securing the communication between Contour and Envoy. If `false`,
                the `contour-certgen` Job will be used to provision certificates.
                If `true`, cert-manager must be installed in the cluster. See: https://github.com/kadras-io/package-for-cert-manager.'
              type: boolean
          type: object
        contour:
          additionalProperties: false
          description: Settings for the Contour component.
          properties:
            config:
              additionalProperties: false
              description: Configuration for the Contour Deployment.
              properties:
                logFormat:
                  default: text
                  description: Log output format for Contour. Either `text` (default)
                    or `json`.
                  type: string
                logLevel:
                  default: info
                  description: The Contour log level. Valid options are `info` and
                    `debug`.
                  type: string
                useProxyProtocol:
                  default: false
                  description: Whether to enable PROXY protocol for all Envoy listeners.
                  type: boolean
              type: object
            configFileContents:
              default: {}
              description: The YAML contents of the Contour config file. See https://projectcontour.io/docs/latest/configuration/#configuration-file
                for more information.
              nullable: true
            replicas:
              default: 2
              description: The number of Contour replicas. In order to enable high
                availability, it should be greater than 1.
              type: integer
          type: object
        envoy:
          additionalProperties: false
          description: Settings for the Envoy component.
          properties:
            config:
              additionalProperties: false
              description: Configuration for the Envoy workload.
              properties:
                logLevel:
                  default: info
                  description: The Envoy log level.
                  type: string
              type: object
            service:
              additionalProperties: false
              description: Envoy service settings.
              properties:
                annotations:
                  default: null
                  description: Annotations to set on the Envoy service.
                  nullable: true
                aws:
                  additionalProperties: false
                  description: AWS-specific settings for the Envoy service. If `infrastructureProvider`
                    is not `aws`, these settings are ignored.
                  properties:
                    loadBalancerType:
                      default: classic
                      description: The type of AWS load balancer to provision. Options
                        are 'classic' and 'nlb'.
                      type: string
                  type: object
                externalTrafficPolicy:
                  default: null
                  description: The external traffic policy for the Envoy service.
                    If type is `ClusterIP`, this field is ignored. Otherwise, it defaults
                    to `Cluster` for vsphere and `Local` for others.
                  nullable: true
                  type: string
                loadBalancerIP:
                  default: ""
                  description: The desired load balancer IP. If `type` is not `LoadBalancer',
                    this field is ignored. It is up to the cloud provider whether
                    to honor this request. If not specified, then load balancer IP
                    will be assigned by the cloud provider.
                  type: string
                nodePorts:
                  additionalProperties: false
                  description: NodePort settings for the Envoy service. If type is
                    not `NodePort` or `LoadBalancer`, these settings are ignored.
                  properties:
                    http:
                      default: 0
                      description: The node port number to expose Envoy's HTTP listener
                        on. If not specified, a node port will be auto-assigned by
                        Kubernetes.
                      type: integer
                    https:
                      default: 0
                      description: The node port number to expose Envoy's HTTPS listener
                        on. If not specified, a node port will be auto-assigned by
                        Kubernetes.
                      type: integer
                  type: object
                type:
                  default: null
                  description: The type of Kubernetes service to provision for Envoy.
                    If not specified, it will default to `NodePort` for local and
                    vsphere and `LoadBalancer` for others.
                  nullable: true
                  type: string
              type: object
            workload:
              additionalProperties: false
              description: Envoy workload settings.
              properties:
                hostNetwork:
                  default: false
                  description: Whether to enable host networking for the Envoy pods.
                  type: boolean
                hostPorts:
                  additionalProperties: false
                  description: Host port settings for the Envoy pods.
                  properties:
                    enabled:
                      default: false
                      description: Whether to enable host ports. If false, http &
                        https are ignored.
                      type: boolean
                    http:
                      default: 80
                      description: If enabled, the host port number to expose Envoy's
                        HTTP listener on.
                      type: integer
                    https:
                      default: 443
                      description: If enabled, the host port number to expose Envoy's
                        HTTPS listener on.
                      type: integer
                  type: object
                replicas:
                  default: 2
                  description: The number of Envoy replicas to deploy when `type`
                    is set to `Deployment`.
                  type: integer
                terminationGracePeriodSeconds:
                  default: 300
                  description: The termination grace period, in seconds, for the Envoy
                    pods.
                  type: integer
                type:
                  default: DaemonSet
                  description: The type of Kubernetes workload that Envoy is deployed
                    as. Options are `Deployment` or `DaemonSet`. If not specified,
                    it defaults to `DaemonSet`.
                  type: string
              type: object
          type: object
        infrastructureProvider:
          default: null
          description: The underlying infrastructure provider. Options are `aws`,
            `azure`, `local` and `vsphere`. This field is not required, but it enables
            better validation and defaulting if provided.
          nullable: true
          type: string
        namespace:
          default: projectcontour
          description: The namespace in which to deploy Contour and Envoy.
          type: string
      type: object
  version: 1.24.3
