apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: postgresql-operator.packages.kadras.io.1.22.2
spec:
  licenses:
  - Apache 2.0
  refName: postgresql-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-postgresql-operator/releases
  releasedAt: "2024-03-15T21:25:50Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-postgresql-operator@sha256:1fc5629346ca0c2889afd5d429777ca83b3fda73d8dfe0c1247d37d76e4fd343
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 1.22.2
