apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: postgresql-operator.packages.kadras.io.1.25.1
spec:
  licenses:
  - Apache 2.0
  refName: postgresql-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-postgresql-operator/releases
  releasedAt: "2025-03-30T09:14:53Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-postgresql-operator@sha256:87d31e3d8b06859553fbd26e60451ff111405fd0eeeee574601225cff0bab69f
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 1.25.1
