apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: spring-boot-conventions.packages.kadras.io.0.2.1
spec:
  licenses:
  - Apache 2.0
  refName: spring-boot-conventions.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-spring-boot-conventions/releases
  releasedAt: "2023-04-09T16:10:20Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-spring-boot-conventions@sha256:94529a2e9bbb279259922a3c7dbdcff67a8442fbfef71e59d5c86f7938e614f5
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: spring-boot-conventions
          description: The namespace where to install Spring Boot Conventions
          type: string
        resources:
          additionalProperties: false
          description: Resource configuration for the Convention Server
          properties:
            limits:
              additionalProperties: false
              description: Resource limits
              properties:
                cpu:
                  default: 100m
                  description: CPU limits
                  type: string
                memory:
                  default: 256Mi
                  description: Memory limits
                  type: string
              type: object
            requests:
              additionalProperties: false
              description: Resource requests
              properties:
                cpu:
                  default: 100m
                  description: CPU requests
                  type: string
                memory:
                  default: 20Mi
                  description: Memory requests
                  type: string
              type: object
          type: object
      type: object
  version: 0.2.1
