apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: spring-boot-conventions.packages.kadras.io
spec:
  categories:
  - ci/cd
  - configuration
  displayName: spring-boot-conventions
  longDescription: The Spring Boot Convention Server works with the Cartographer Convention
    Controller to apply best-practices to workloads at runtime by understanding the
    developer's intent.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Spring Boot Convention Server for Cartographer.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-spring-boot-conventions
    for community support.
