apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: application-platform.packages.kadras.io
spec:
  categories:
  - internal developer platform
  - application platform
  displayName: application-platform
  longDescription: A curated set of Carvel packages to build an application platform
    or internal developer platform (IDP) on Kubernetes.
  maintainers:
  - name: Thomas Vitale
  providerName: Arktonix
  shortDescription: Application platform on Kubernetes.
