apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: application-platform.packages.kadras.io
spec:
  categories:
  - internal developer platform
  - application platform
  displayName: application-platform
  longDescription: A curated set of Carvel packages to build an engineering platform
    supporting application developers with paved paths to production on Kubernetes.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Cloud native application platform on Kubernetes.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/kadras-application-platform
    for community support.
