apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer.packages.kadras.io.0.7.1
spec:
  refName: cartographer.packages.kadras.io
  version: 0.7.1
  releaseNotes: https://github.com/vmware-tanzu/package-for-cartographer/releases/tag/0.7.1
  releasedAt: "2023-03-10T18:38:54Z"
  valuesSchema:
    openAPIv3:
      title: cartographer.packages.kadras.io.0.7.1 values schema
      properties:
        ca_cert_data:
          type: string
          description: 'Optional: PEM Encoded certificate data for image registries with private CA.'
          default: ""
        excluded_components:
          type: array
          items:
            type: string
          default: []
          description: 'Optional: List of components to exclude from installation (e.g. [conventions])'
        aws_iam_role_arn:
          type: string
          description: 'Optional: Arn role that has access to pull images from ECR container registry'
          default: ""
        cartographer:
          type: object
          properties:
            concurrency:
              type: object
              properties:
                max_workloads:
                  type: integer
                  description: 'Optional: maximum number of Workloads to process concurrently.'
                  default: 2
                max_deliveries:
                  type: integer
                  description: 'Optional: maximum number of Deliverables to process concurrently.'
                  default: 2
                max_runnables:
                  type: integer
                  description: 'Optional: maximum number of Runnables to process concurrently.'
                  default: 2
            resources:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    cpu:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: maximum amount of cpu resources to allow the controller to use'
                      default: 1000m
                    memory:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: maximum amount of memory to allow the controller to use'
                      default: 128Mi
                requests:
                  type: object
                  properties:
                    cpu:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: minimum amount of cpu to reserve'
                      default: 250m
                    memory:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: minimum amount of memory to reserve'
                      default: 128Mi
        conventions:
          type: object
          properties:
            resources:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    cpu:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: maximum amount of cpu resources to allow the controller to use'
                      default: 1000m
                    memory:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: maximum amount of memory to allow the controller to use'
                      default: 128Mi
                requests:
                  type: object
                  properties:
                    cpu:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: minimum amount of cpu to reserve'
                      default: 250m
                    memory:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                      description: 'Optional: minimum amount of memory to reserve'
                      default: 128Mi
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/projectcartographer/package-for-cartographer@sha256:e39f96dc9b778f81a83e55dd5f30eb38d3f92469787b9152fc1190e1e5de9050
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - config
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
