apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cartographer.packages.kadras.io
spec:
  categories:
  - supply chains
  - golden paths
  displayName: cartographer
  longDescription: A Kubernetes-native solution to design and build paved paths to
    production. Using the choreography pattern, it configures Kubernetes resources
    into reusable supply chains that can be used to define all the stages of a path
    from the developer laptop to production.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Kubernetes-native framework to build paved paths to production.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-cartographer
    for community support.
