apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: gitops-configurer.packages.kadras.io
spec:
  categories:
  - gitops
  displayName: gitops-configurer
  longDescription: Simplify onboarding of GitOps workflows based on Carvel or Flux.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Simplify onboarding of GitOps workflows.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/gitops-configurer
    for community support.
