apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.5.1
spec:
  licenses:
  - Apache 2.0
  refName: cartographer-blueprints.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/cartographer-blueprints/releases
  releasedAt: "2023-04-01T15:36:14Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/cartographer-blueprints@sha256:c9d33e5018c6b5c1a3c60a5416404cb0e5c307bcfda43028505722c4a1eaf669
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          default: []
          description: A list of blueprints and manifests to esclude from being created
            in the cluster.
          items:
            default: ""
            type: string
          type: array
        tekton_catalog_namespace:
          default: tekton-catalog
          description: The namespace where the Tekton Catalog package has been installed.
          type: string
      type: object
  version: 0.5.1
