apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.7.1
spec:
  licenses:
  - Apache 2.0
  refName: cartographer-blueprints.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/cartographer-blueprints/releases
  releasedAt: "2023-09-06T19:36:11Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/cartographer-blueprints@sha256:77837b0e2ff90f6da631b6e34c9b3fc5d6bfdd1c30517b6c427e42218892cf1a
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          default: []
          description: A list of blueprints to esclude from being created in the cluster.
          items:
            default: ""
            type: string
          type: array
        tekton_catalog_namespace:
          default: tekton-catalog
          description: The namespace where the Tekton Catalog package has been installed.
          type: string
      type: object
  version: 0.7.1
