apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.7.2
spec:
  licenses:
  - Apache 2.0
  refName: cartographer-blueprints.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/cartographer-blueprints/releases
  releasedAt: "2023-09-08T15:37:38Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/cartographer-blueprints@sha256:3522ca1a956134a57107cb915c29bfbf9df417fdfc29649ccd18daac4f12b356
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          default: []
          description: A list of blueprints to esclude from being created in the cluster.
          items:
            default: ""
            type: string
          type: array
        tekton_catalog_namespace:
          default: tekton-catalog
          description: The namespace where the Tekton Catalog package has been installed.
          type: string
      type: object
  version: 0.7.2
