apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kpack-dependencies.packages.kadras.io.0.4.1
spec:
  capacityRequirementsDescription: Container registry with > 1GB available space
  licenses:
  - Apache 2.0
  refName: kpack-dependencies.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/kpack-dependencies/releases
  releasedAt: "2023-03-19T10:28:35Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/kpack-dependencies@sha256:4dfee58e34f34404b233abb5e2f60243cc4da61d84e63e7ed7ab0fd33b2c8264
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        kp_default_repository:
          additionalProperties: false
          description: Settings for the default container repository used by kpack.
            Same as configured in the kpack package.
          properties:
            name:
              default: ""
              description: The default repository where to publish builder images
                and dependencies.
              example: ghcr.io/thomasvitale/kpack
              type: string
              x-example-description: Repository on GitHub Container Registry
          type: object
      type: object
  version: 0.4.1
