apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kpack.packages.kadras.io.0.15.0
spec:
  capacityRequirementsDescription: Container registry with > 1GB available space
  licenses:
  - Apache 2.0
  refName: kpack.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-kpack/releases
  releasedAt: "2024-07-29T20:23:23Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-kpack@sha256:c0f573f867f22a06a1c0d107ed309cc49bd399070a067be74a916738c923d81d
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        ca_cert_data:
          default: ""
          description: 'PEM-encoded certificate data that kpack controller will use
            to trust TLS connections based on a custom CA with a container registry.
            Note: This will not be injected into builds, you need to use the cert
            injection webhook with the `kpack.io/build` label value.'
          type: string
        config:
          additionalProperties: false
          description: Settings for kpack.
          properties:
            injected_sidecar_support:
              default: false
              description: Enable support for injected sidecars.
              type: boolean
          type: object
        controller:
          additionalProperties: false
          description: Settings for the the kpack controller.
          properties:
            resources:
              additionalProperties: false
              description: Resource configuration for the kpack-controller Deployment.
              properties:
                limits:
                  additionalProperties: false
                  properties:
                    memory:
                      default: 1Gi
                      description: Memory limits configuration for the kpack-controller
                        Deployment. In a resource-constrained environment, you can
                        lower this up to `500Mi`.
                      type: string
                  type: object
                requests:
                  additionalProperties: false
                  properties:
                    memory:
                      default: 1Gi
                      description: Memory requests configuration for the kpack-controller
                        Deployment. In a resource-constrained environment, you can
                        lower this up to `100Mi`.
                      type: string
                  type: object
              type: object
          type: object
        kp_default_repository:
          additionalProperties: false
          description: Settings for the default container repository used by kpack.
          properties:
            aws_iam_role_arn:
              default: null
              description: IAM credentials to access the default container repository
                if the registry is on AWS.
              nullable: true
              type: string
            credentials:
              additionalProperties: false
              description: Read/write credentials to access the default container
                repository.
              nullable: true
              properties:
                password:
                  default: ""
                  description: 'Token to access the default container repository.
                    Note: Use contents of service account key json for GCR.'
                  type: string
                username:
                  default: ""
                  description: 'Username to access the default container repository.
                    Note: Use `_json_key` for GCR.'
                  type: string
              type: object
            name:
              default: ""
              description: The default repository to use for builder images and dependencies.
              example: ghcr.io/thomasvitale/buildpacks
              minLength: 1
              type: string
              x-example-description: Repository on GitHub Container Registry
            secret:
              additionalProperties: false
              description: Configuration for the Secret holding the credentials to
                access the default container repository.
              nullable: true
              properties:
                create_export:
                  default: false
                  description: Whether to create a SecretExport resource to export
                    the Secret from the source namespace to the kpack namespace. Not
                    needed when installing kpack as part of the Kadras Enginnering
                    Platform.
                  type: boolean
                name:
                  default: ""
                  description: The name of the Secret holding the credentials to access
                    the default container repository.
                  type: string
                namespace:
                  default: ""
                  description: The namespace of the Secret holding the credentials
                    to access the default container repository.
                  type: string
              type: object
          type: object
        proxy:
          additionalProperties: false
          description: Settings for the corporate proxy.
          properties:
            http_proxy:
              default: ""
              description: The HTTP proxy to use for network traffic
              type: string
            https_proxy:
              default: ""
              description: The HTTPS proxy to use for network traffic
              type: string
            no_proxy:
              default: ""
              description: A comma-separated list of hostnames, IP addresses, or IP
                ranges in CIDR format that should not use a proxy (e.g. Kubernetes
                API address).
              type: string
          type: object
      type: object
  version: 0.15.0
