apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: rbac-configurer.packages.kadras.io
spec:
  categories:
  - rbac
  displayName: rbac-configurer
  longDescription: Default roles and RBAC configuration for the Kadras Engineering
    Platform, supporting users and service accounts.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Default roles and RBAC configuration for the Kadras Engineering
    Platform.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/rbac-configurer
    for community support.
