apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: tekton-catalog.packages.kadras.io.0.2.3
spec:
  licenses:
  - Apache 2.0
  refName: tekton-catalog.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/tekton-catalog/releases
  releasedAt: "2023-10-13T18:59:40Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/tekton-catalog@sha256:d829bb143c0f6336986d7022daa4397b7ab946acd2ec78812cad1c343e9bb3bd
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: tekton-catalog
          description: The namespace where to deploy the Tekton Catalog.
          type: string
      type: object
  version: 0.2.3
