apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: tekton-catalog.packages.kadras.io
spec:
  categories:
  - build
  displayName: tekton-catalog
  longDescription: A set of Tekton pipelines and tasks used by the Kadras platform
    to support testing, scanning, delivering and deploying applications.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: A set of Tekton pipelines and tasks to use with the Kadras platform.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/tekton-catalog
    for community support.
