apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: namespace-setup.packages.kadras.io
spec:
  categories:
  - environment provisioning
  displayName: namespace-setup
  longDescription: namespace-setup.packages.kadras.io
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: namespace-setup.packages.kadras.io
