apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: buildpacks-catalog.packages.kadras.io.0.5.0
spec:
  capacityRequirementsDescription: Container registry with > 1GB available space
  licenses:
  - Apache 2.0
  refName: buildpacks-catalog.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/buildpacks-catalog/releases
  releasedAt: "2023-03-20T16:49:46Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/buildpacks-catalog@sha256:f6dc63199b4f3b98ee155f2380268cb8819529aab3b777672279f3d414fbf51a
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        kp_default_repository:
          additionalProperties: false
          description: Settings for the default container repository used by kpack.
            Same as configured in the kpack package.
          properties:
            name:
              default: ""
              description: The default repository where to publish builder images
                and dependencies.
              example: ghcr.io/thomasvitale/kpack-build
              type: string
              x-example-description: Repository on GitHub Container Registry
          type: object
      type: object
  version: 0.5.0
