apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: rabbitmq-operator.packages.kadras.io.2.11.0
spec:
  licenses:
  - Apache 2.0
  refName: rabbitmq-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-rabbitmq-operator/releases
  releasedAt: "2024-10-23T15:52:14Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-rabbitmq-operator@sha256:b510e8dd5b1da589f69fcf9882f0f0444840f32fac66d088f1cafc78aef6d1d4
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        logging:
          additionalProperties: false
          description: Logging configuration.
          properties:
            level:
              default: info
              description: The Operator log level. Valid options are `info` and `debug`.
              enum:
              - info
              - debug
              type: string
          type: object
      type: object
  version: 2.11.0
