apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: rabbitmq-operator.packages.kadras.io.2.13.0
spec:
  licenses:
  - Apache 2.0
  refName: rabbitmq-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-rabbitmq-operator/releases
  releasedAt: "2025-05-30T19:52:33Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-rabbitmq-operator@sha256:5055748f058a71d03389a18b7f0a5c3c2dc00d5797c6aaa24b2fb6680eb8ab0f
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        logging:
          additionalProperties: false
          description: Logging configuration.
          properties:
            level:
              default: info
              description: The Operator log level. Valid options are `info` and `debug`.
              enum:
              - info
              - debug
              type: string
          type: object
      type: object
  version: 2.13.0
