apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: rabbitmq-operator.packages.kadras.io.2.19.0
spec:
  licenses:
  - Apache 2.0
  refName: rabbitmq-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-rabbitmq-operator/releases
  releasedAt: "2026-02-01T20:02:24Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-rabbitmq-operator@sha256:f3bbd5144b17db295cbdc2669300d46681f6d1cede2a5476e04aa7f786dff628
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        logging:
          additionalProperties: false
          description: Logging configuration.
          properties:
            level:
              default: info
              description: The Operator log level. Valid options are `info` and `debug`.
              enum:
              - info
              - debug
              type: string
          type: object
      type: object
  version: 2.19.0
