apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: rabbitmq-operator.packages.kadras.io.2.7.0
spec:
  licenses:
  - Apache 2.0
  refName: rabbitmq-operator.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-rabbitmq-operator/releases
  releasedAt: "2024-03-08T20:44:42Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-rabbitmq-operator@sha256:cde3242a79272d09c24578997b8272773fc44909ae754aed11159dc610204679
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        logging:
          additionalProperties: false
          description: Logging configuration.
          properties:
            level:
              default: info
              description: The Operator log level. Valid options are `info` and `debug`.
              type: string
          type: object
      type: object
  version: 2.7.0
