apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: rabbitmq-operator.packages.kadras.io
spec:
  categories:
  - eventing
  - messaging
  - streaming
  displayName: rabbitmq-operator
  longDescription: Operator for RabbitMQ, an open-source message broker supporting
    multiple messaging protocols and streaming.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Operator for RabbitMQ, a message broker supporting multiple messaging
    protocols and streaming.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-rabbitmq-operator
    for community support.
