apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kyverno.packages.kadras.io.1.10.3
spec:
  licenses:
  - Apache 2.0
  refName: kyverno.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-kyverno/releases
  releasedAt: "2023-08-22T13:33:51Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-kyverno@sha256:a515d5139f402f1f74c96173cc6cb1840cde4cfbac5ec81c4470d7054d846b8d
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 1.10.3
