apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-delivery.packages.kadras.io.0.5.0
spec:
  refName: cartographer-delivery.packages.kadras.io
  releasedAt: "2023-08-19T13:05:25Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/cartographer-delivery@sha256:236e9fc286f347b1de82fe55038ebd6415e22811fa004e912817f79951b6b660
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        delivery_chain:
          default: basic
          description: 'The type of delivery chain to use when deploying workloads.
            Options: `basic`.'
          type: string
        git_credentials_secret:
          default: ""
          description: The Secret containing authentication credentials for Git repositories.
          type: string
        service_account:
          default: default
          description: The default `ServiceAccount` used by the delivery chain.
          type: string
      type: object
  version: 0.5.0
