apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argo-cd.packages.kadras.io.2.6.7
spec:
  licenses:
  - Apache 2.0
  refName: argo-cd.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-argo-cd/releases
  releasedAt: "2023-04-13T20:46:52Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-argo-cd@sha256:3c17becac8f60bdc2e2b407e70ef7ea84ad3577e5269581db5ce62e217ff8676
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: argocd
          description: The namespace where to install Argo CD
          type: string
        service:
          additionalProperties: false
          description: Service configuration for the Argo CD Server
          properties:
            type:
              default: ClusterIP
              description: The Service type for the Argo CD Server
              type: string
          type: object
      type: object
  version: 2.6.7
