apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argo-cd.packages.kadras.io.2.9.3
spec:
  licenses:
  - Apache 2.0
  refName: argo-cd.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-argo-cd/releases
  releasedAt: "2023-12-15T23:57:22Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/kadras-io/package-for-argo-cd@sha256:c616a26d83d522ec73aae3697acfc9e84136be31e884d15b884e9b45fd003acf
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        namespace:
          default: argocd
          description: The namespace where to install Argo CD
          type: string
        service:
          additionalProperties: false
          description: Service configuration for the Argo CD Server
          properties:
            type:
              default: ClusterIP
              description: The Service type for the Argo CD Server
              type: string
          type: object
      type: object
  version: 2.9.3
